import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: {
    default: "Union Rep",
    template: "%s | Union Rep"
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="da"
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
    >
      <body>{children}</body>
    </html>
  );
}
